spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port:
    8080